name: Update Adlist

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  update-adlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and merge adlists
        run: |
          # Create a empty file for the compined adblocklists
          echo "# Custom Combined Adlist" > adlist.txt

          # Download every URL from sources.txt und add them to adlist.txt
          while read -r url; do
            echo "Adding $url..."
            curl -s "$url" | grep -v "^#" >> adlist.txt
          done < sources.txt

          # Removed duplicate entries
          sort -u -o adlist.txt adlist.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "GitHub Action"
          git add adlist.txt
          git commit -m "Update adlist on $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
